export const resumeTemplates = [
  {
    id: 'modern',
    name: 'Modern',
    description: 'Clean and contemporary design with subtle colors',
    thumbnail: '/templates/modern.png',
    color: '#3B82F6',
    category: 'modern',
    atsScore: 95,
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional resume format with a professional look',
    thumbnail: '/templates/classic.png',
    color: '#1F2937',
    category: 'simple',
    atsScore: 98,
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Modern with creative touches and visual elements',
    thumbnail: '/templates/creative.png',
    color: '#EC4899',
    category: 'modern',
    atsScore: 85,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Minimalist design focusing on content',
    thumbnail: '/templates/minimal.png',
    color: '#6B7280',
    category: 'simple',
    atsScore: 96,
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'Corporate professional resume template',
    thumbnail: '/templates/professional.png',
    color: '#0891B2',
    category: 'professional',
    atsScore: 97,
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Senior-level executive resume with elegant styling',
    thumbnail: '/templates/executive.png',
    color: '#7C3AED',
    category: 'professional',
    atsScore: 94,
  },
  {
    id: 'tech',
    name: 'Tech Pro',
    description: 'Perfect for software developers and IT professionals',
    thumbnail: '/templates/tech.png',
    color: '#10B981',
    category: 'modern',
    atsScore: 96,
  },
  {
    id: 'designer',
    name: 'Designer',
    description: 'Creative layout for designers and artists',
    thumbnail: '/templates/designer.png',
    color: '#F59E0B',
    category: 'creative',
    atsScore: 82,
  },
  {
    id: 'academic',
    name: 'Academic',
    description: 'Ideal for researchers, professors and educators',
    thumbnail: '/templates/academic.png',
    color: '#8B5CF6',
    category: 'professional',
    atsScore: 93,
  },
  {
    id: 'compact',
    name: 'Compact',
    description: 'Space-efficient single column layout',
    thumbnail: '/templates/compact.png',
    color: '#64748B',
    category: 'one-column',
    atsScore: 99,
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Sophisticated design with premium feel',
    thumbnail: '/templates/elegant.png',
    color: '#BE185D',
    category: 'professional',
    atsScore: 91,
  },
  {
    id: 'bold',
    name: 'Bold',
    description: 'Stand out with strong typography and colors',
    thumbnail: '/templates/bold.png',
    color: '#DC2626',
    category: 'creative',
    atsScore: 88,
  },
  {
    id: 'infographic',
    name: 'Infographic',
    description: 'Visual resume with charts and progress bars',
    thumbnail: '/templates/infographic.png',
    color: '#0EA5E9',
    category: 'creative',
    atsScore: 75,
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Career progression in a timeline format',
    thumbnail: '/templates/timeline.png',
    color: '#14B8A6',
    category: 'modern',
    atsScore: 87,
  },
  {
    id: 'photo-sidebar',
    name: 'Photo Sidebar',
    description: 'Resume with profile photo on sidebar',
    thumbnail: '/templates/photo-sidebar.png',
    color: '#6366F1',
    category: 'with-photo',
    atsScore: 80,
  },
  {
    id: 'ats-optimized',
    name: 'ATS Optimized',
    description: 'Maximum ATS compatibility with clean formatting',
    thumbnail: '/templates/ats-optimized.png',
    color: '#22C55E',
    category: 'ats',
    atsScore: 100,
  },
];

export const defaultResume = {
  title: 'My Resume',
  template: 'modern',
  personalInfo: {
    fullName: '',
    email: '',
    phone: '',
    location: '',
    professionalSummary: '',
    profileImage: '',
  },
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: [],
  languages: [],
};
