export const resumeTemplates = [
  {
    id: 'modern',
    name: 'Modern',
    description: 'Clean and contemporary design with subtle colors',
    thumbnail: '/templates/modern.png',
    color: '#3B82F6',
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional resume format with a professional look',
    thumbnail: '/templates/classic.png',
    color: '#1F2937',
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Modern with creative touches and visual elements',
    thumbnail: '/templates/creative.png',
    color: '#EC4899',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Minimalist design focusing on content',
    thumbnail: '/templates/minimal.png',
    color: '#6B7280',
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'Corporate professional resume template',
    thumbnail: '/templates/professional.png',
    color: '#0891B2',
  },
];

export const atsKeywords = {
  hardSkills: [
    'javascript',
    'python',
    'java',
    'react',
    'nodejs',
    'typescript',
    'sql',
    'mongodb',
    'aws',
    'docker',
    'git',
    'html',
    'css',
    'api',
    'rest',
    'graphql',
    'linux',
    'kubernetes',
  ],
  softSkills: [
    'communication',
    'leadership',
    'teamwork',
    'problem-solving',
    'critical thinking',
    'time management',
    'creativity',
    'collaboration',
    'adaptability',
    'analytical',
  ],
  actionVerbs: [
    'developed',
    'implemented',
    'designed',
    'created',
    'managed',
    'led',
    'achieved',
    'improved',
    'optimized',
    'delivered',
    'coordinated',
    'executed',
  ],
};
